"""update schema to match models

Revision ID: 834157ecbf96
Revises: 
Create Date: 2024-11-24 15:25:05.052809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '834157ecbf96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MovieAdaptationUser', schema=None) as batch_op:
        batch_op.drop_index('IX_MovieAdaptationUser_WatchersUserId')

    op.drop_table('MovieAdaptationUser')
    op.drop_table('adaptations')
    with op.batch_alter_table('MovieAdaptationUser1', schema=None) as batch_op:
        batch_op.drop_index('IX_MovieAdaptationUser1_WatchlistedByUserId')

    op.drop_table('MovieAdaptationUser1')
    op.drop_table('__EFMigrationsHistory')
    with op.batch_alter_table('BookUser', schema=None) as batch_op:
        batch_op.drop_index('IX_BookUser_ReadersUserId')

    op.drop_table('BookUser')
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('Author',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('PublicationDate',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('ISBN',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('GoogleBooksId',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('Description',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('CoverImageUrl',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('PageCount',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('Rating',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('Review',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))

    with op.batch_alter_table('MovieAdaptations', schema=None) as batch_op:
        batch_op.alter_column('Title',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('Overview',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('ReleaseDate',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('TmdbId',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('PosterPath',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))
        batch_op.drop_index('IX_MovieAdaptations_BookId')
        batch_op.drop_constraint('FK_MovieAdaptations_Books_BookId', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Books', ['BookId'], ['BookId'])

    with op.batch_alter_table('Reviews', schema=None) as batch_op:
        batch_op.alter_column('MovieAdaptationId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Rating',
               existing_type=mssql.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('Comment',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.drop_index('IX_Reviews_MovieAdaptationId')
        batch_op.drop_index('IX_Reviews_UserId')
        batch_op.drop_constraint('FK_Reviews_MovieAdaptations_MovieAdaptationId', type_='foreignkey')
        batch_op.drop_constraint('FK_Reviews_Users_UserId', type_='foreignkey')
        batch_op.create_foreign_key(None, 'MovieAdaptations', ['MovieAdaptationId'], ['MovieAdaptationId'])
        batch_op.create_foreign_key(None, 'Users', ['UserId'], ['UserId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK_Reviews_Users_UserId', 'Users', ['UserId'], ['UserId'], ondelete='CASCADE')
        batch_op.create_foreign_key('FK_Reviews_MovieAdaptations_MovieAdaptationId', 'MovieAdaptations', ['MovieAdaptationId'], ['MovieAdaptationId'], ondelete='CASCADE')
        batch_op.create_index('IX_Reviews_UserId', ['UserId'], unique=False)
        batch_op.create_index('IX_Reviews_MovieAdaptationId', ['MovieAdaptationId'], unique=False)
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               nullable=False)
        batch_op.alter_column('Comment',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('Rating',
               existing_type=sa.Float(),
               type_=mssql.REAL(),
               existing_nullable=False)
        batch_op.alter_column('MovieAdaptationId',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('MovieAdaptations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK_MovieAdaptations_Books_BookId', 'Books', ['BookId'], ['BookId'], ondelete='CASCADE')
        batch_op.create_index('IX_MovieAdaptations_BookId', ['BookId'], unique=False)
        batch_op.alter_column('PosterPath',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('TmdbId',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('ReleaseDate',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
        batch_op.alter_column('Overview',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('Title',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))

    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('Review',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('Rating',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('PageCount',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('CoverImageUrl',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('Description',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('GoogleBooksId',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('ISBN',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))
        batch_op.alter_column('PublicationDate',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
        batch_op.alter_column('Author',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("(N'')"))

    op.create_table('BookUser',
    sa.Column('ReadHistoryBookId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ReadersUserId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ReadHistoryBookId'], ['Books.BookId'], name='FK_BookUser_Books_ReadHistoryBookId', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ReadersUserId'], ['Users.UserId'], name='FK_BookUser_Users_ReadersUserId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ReadHistoryBookId', 'ReadersUserId', name='PK_BookUser')
    )
    with op.batch_alter_table('BookUser', schema=None) as batch_op:
        batch_op.create_index('IX_BookUser_ReadersUserId', ['ReadersUserId'], unique=False)

    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.NVARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name='PK___EFMigrationsHistory')
    )
    op.create_table('MovieAdaptationUser1',
    sa.Column('WatchlistMovieAdaptationId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('WatchlistedByUserId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['WatchlistMovieAdaptationId'], ['MovieAdaptations.MovieAdaptationId'], name='FK_MovieAdaptationUser1_MovieAdaptations_WatchlistMovieAdaptationId', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['WatchlistedByUserId'], ['Users.UserId'], name='FK_MovieAdaptationUser1_Users_WatchlistedByUserId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('WatchlistMovieAdaptationId', 'WatchlistedByUserId', name='PK_MovieAdaptationUser1')
    )
    with op.batch_alter_table('MovieAdaptationUser1', schema=None) as batch_op:
        batch_op.create_index('IX_MovieAdaptationUser1_WatchlistedByUserId', ['WatchlistedByUserId'], unique=False)

    op.create_table('adaptations',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('movieID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bookID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('adaptation_type', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bookID'], ['Books.BookId'], name='FK__adaptatio__bookI__151B244E'),
    sa.ForeignKeyConstraint(['movieID'], ['movies.movieID'], name='FK__adaptatio__movie__14270015'),
    sa.PrimaryKeyConstraint('id', name='PK__adaptati__3213E83F5749FE6D')
    )
    op.create_table('MovieAdaptationUser',
    sa.Column('WatchHistoryMovieAdaptationId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('WatchersUserId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['WatchHistoryMovieAdaptationId'], ['MovieAdaptations.MovieAdaptationId'], name='FK_MovieAdaptationUser_MovieAdaptations_WatchHistoryMovieAdaptationId', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['WatchersUserId'], ['Users.UserId'], name='FK_MovieAdaptationUser_Users_WatchersUserId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('WatchHistoryMovieAdaptationId', 'WatchersUserId', name='PK_MovieAdaptationUser')
    )
    with op.batch_alter_table('MovieAdaptationUser', schema=None) as batch_op:
        batch_op.create_index('IX_MovieAdaptationUser_WatchersUserId', ['WatchersUserId'], unique=False)

    # ### end Alembic commands ###
