"""Update Movie model attributes

Revision ID: b52055a2ad96
Revises: d4aa68547464
Create Date: 2024-11-28 13:16:11.626798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52055a2ad96'
down_revision = 'd4aa68547464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vote_average', sa.Float(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('tmdb_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('average_rating')
        batch_op.drop_column('runtime')
        batch_op.drop_column('releaseDate')
        batch_op.drop_column('genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('releaseDate', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('runtime', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('average_rating', sa.FLOAT(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('tmdb_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.drop_column('vote_average')
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
