"""Add ReadingList table

Revision ID: d4aa68547464
Revises: d4f7740292be
Create Date: 2024-11-28 13:10:32.027963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4aa68547464'
down_revision = 'd4f7740292be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WatchHistory')
    op.drop_table('ReadingList')
    op.drop_table('ReadHistory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ReadHistory',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bookID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('read_date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bookID'], ['Books.BookId'], name='FK__ReadHisto__bookI__178D7CA5'),
    sa.ForeignKeyConstraint(['userID'], ['Users.UserId'], name='FK__ReadHisto__userI__1699586C'),
    sa.PrimaryKeyConstraint('id', name='PK__ReadHist__3213E83F6AA670ED')
    )
    op.create_table('ReadingList',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bookID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_date', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bookID'], ['Books.BookId'], name='FK__ReadingLi__bookI__1B5E0D89'),
    sa.ForeignKeyConstraint(['userID'], ['Users.UserId'], name='FK__ReadingLi__userI__1A69E950'),
    sa.PrimaryKeyConstraint('id', name='PK__ReadingL__3213E83FFD82F8D1')
    )
    op.create_table('WatchHistory',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movieID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('watched_date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movieID'], ['movies.movieID'], name='FK__WatchHist__movie__13BCEBC1'),
    sa.ForeignKeyConstraint(['userID'], ['Users.UserId'], name='FK__WatchHist__userI__12C8C788'),
    sa.PrimaryKeyConstraint('id', name='PK__WatchHis__3213E83F13139B11')
    )
    # ### end Alembic commands ###
